version: '3'

services:

  database:
    ports:
      - 5432:5432
    volumes:
      - "database_volume:/var/lib/postgresql/data"

  backend:
    tty: true
    volumes:
      - type: bind
        source: ./srcs/backend
        target: /app
    ports:
      - 3000:3000
    entrypoint: bash

  frontend:
    build:
      context: ./
      dockerfile: ./requirements/frontend/Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - ./srcs/frontend/.env-dev
    tty: true
    volumes:
      - type: bind
        source: ./srcs/frontend
        target: /app
    ports:
      - 5173:5173
    entrypoint: bash

  nginx:
    entrypoint: bash

volumes:
    database_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "./data"
