version: '3'

services:
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
     - "4000:4000"
    volumes:
     - ./docs/:/app/
  database:
    image: 'postgres:15.0'
    container_name: database
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - "database_volume:/var/lib/postgresql/data"
  backend:
    image: 'nestjs/cli'
    container_name: backend
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./srcs
        target: /app
    ports:
      - 3000:3000

volumes:
    database_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "./data"
