version: '3'

services:

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    container_name: docs
    ports:
     - "4000:4000"
    volumes:
     - ./docs/:/app/

  database:
    image: 'postgres:bullseye'
    container_name: database
    restart: always
    env_file:
      - ./.env
    volumes:
      - "database_volume:/var/lib/postgresql/data"

  backend:
    build:
      context: ./
      dockerfile: ./requirements/backend/Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pixelizer:
    build:
      context: ./
      dockerfile: ./requirements/pixelizer/Dockerfile
    container_name: pixelizer
    restart: always
    environment:
      - WORK_PATH=/app

  nginx:
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
    database_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "./data"
